version: '3.7'

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo

    volumes:
      - './docker/mysql/start-fixture.sql:/docker-entrypoint-initdb.d/start-fixture.sql'

    ports:
      - '3306:3306'

  mongo:
    image: mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: demo

    volumes:
      - './docker/mongo/start-fixture.js:/docker-entrypoint-initdb.d/start-fixture.js'

    ports:
      - '27017:27017'