version: '3.7'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo

    volumes:
      - './docker/mysql/start-fixture.sql:/docker-entrypoint-initdb.d/start-fixture.sql'

    ports:
      - '3306:3306'